#!/bin/bash

cd "$(dirname "$0")"

echo "PHP pid:	$(< .tlb/php.pid);	TOR pid:	$(< .tlb/tor.pid)"
echo HTTP address:
echo "	http://$(cat .tlb/http_address)"
echo TOR address:
echo "	$(cat .tlb/tor-hidden-service/hostname)"
