#!/bin/bash

set -e

cd "$(dirname "$0")"

dir="$(realpath "${1:-.tlb}")"
pid_file="$dir/php.pid"
addr_file="$dir/http_address"

echo $BASHPID > "$pid_file"

export PHP_CLI_SERVER_WORKERS=3

exec php -S "$(< "$addr_file")" -t public_html
